name: khadmli_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.3.2
  shared_preferences: ^2.2.1
  provider: ^6.1.1
  image_picker: ^1.0.4
  file_picker: ^8.0.0
  cached_network_image: ^3.3.0
  intl: ^0.18.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"  # Ton logo (1024x1024px)
  adaptive_icon_background: "#BE5103"  # Couleur de fond orange
  adaptive_icon_foreground: "assets/icon_foreground.png"

flutter:
  uses-material-design: true