"""add skill_vector and task_vector

Revision ID: b8436e519520
Revises: 
Create Date: 2026-04-15 01:40:10.450400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8436e519520'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task_vector', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('skill_vector', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'skill_vector')
    op.drop_column('tasks', 'task_vector')
    # ### end Alembic commands ###
